# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 18:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidade', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDetalhe',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_usuario', models.CharField(choices=[('O', 'Organizador'), ('P', 'Participante')], max_length=1, verbose_name='Tipo do usuário')),
                ('email_pagseguro', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail PagSeguro')),
                ('token_pagseguro', models.CharField(blank=True, max_length=300, null=True, verbose_name='Token PagSeguro')),
                ('foto_usuario', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto do perfil')),
                ('telefone', models.CharField(max_length=10, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP/ZIP-Code')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('numero_endereco', models.IntegerField(verbose_name='Número')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outros')], max_length=1, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('numero_identidade', models.CharField(max_length=20, verbose_name='Identidade')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidade.Cidade', verbose_name='Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidade.Estado', verbose_name='Estado')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidade.Pais', verbose_name='País')),
            ],
            options={
                'db_table': 'UsuarioDetalhe',
                'verbose_name': 'Usuários',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
