# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodetalhe',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuariodetalhe',
            name='pais',
        ),
    ]
