# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('palavras_chave', models.CharField(max_length=100, verbose_name='Palavras chave')),
                ('tipo_cobranca', models.CharField(choices=[('G', 'Gratuito'), ('P', 'Pago')], max_length=1, verbose_name='Tipo de combrança')),
                ('evento_privado', models.BooleanField(verbose_name='Evento privado ?')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP/ZIP-Code')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('numero_endereco', models.IntegerField(verbose_name='Número')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_arquivo', models.FileField(upload_to='', verbose_name='Arquivo')),
                ('nome_arquivo', models.CharField(max_length=50, verbose_name='Nome do anexo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(max_length=5, verbose_name='Nota')),
                ('comentario', models.TextField(verbose_name='Comentário')),
            ],
        ),
        migrations.CreateModel(
            name='EventoOrganizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EventoPalestrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.TextField(verbose_name='Descrição do palestrante')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='EventoParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventoPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do evento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora do inicio')),
                ('hora_fim', models.TimeField(verbose_name='Hora do fim')),
                ('quantidade_vagas', models.IntegerField(verbose_name='Quantidade de vagas')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventoVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('YT', 'Youtube'), ('VM', 'VIMEO')], max_length=3, verbose_name='Plataforma')),
                ('url', models.URLField(verbose_name='Link para o vídeo')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
        ),
        migrations.AddField(
            model_name='eventoparticipante',
            name='evento_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.EventoPeriodo'),
        ),
    ]
