# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20160612_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopalestrante',
            name='Descricao',
            field=models.TextField(default=None, verbose_name='Descrição do palestrante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventoavaliacao',
            name='nota',
            field=models.IntegerField(verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='eventopalestrante',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
    ]
