# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_usuariodetalhe'),
        ('localidade', '0002_auto_20160821_1434'),
        ('evento', '0002_auto_20160821_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoparticipante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.UsuarioDetalhe'),
        ),
        migrations.AddField(
            model_name='eventopalestrante',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='eventoorganizador',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='eventoorganizador',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.UsuarioDetalhe'),
        ),
        migrations.AddField(
            model_name='eventocomentario',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='eventocomentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.UsuarioDetalhe'),
        ),
        migrations.AddField(
            model_name='eventoanexo',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidade.Cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.EventoTipo', verbose_name='Tipo do evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.UsuarioDetalhe'),
        ),
    ]
