# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_auto_20160612_1552'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='Evento',
        ),
        migrations.AlterModelTable(
            name='eventoanexo',
            table='EventoAnexo',
        ),
        migrations.AlterModelTable(
            name='eventoavaliacao',
            table='EventoAvaliacao',
        ),
        migrations.AlterModelTable(
            name='eventoorganizador',
            table='EventoOrganizador',
        ),
        migrations.AlterModelTable(
            name='eventopalestrante',
            table='EventoPalestrante',
        ),
        migrations.AlterModelTable(
            name='eventoparticipante',
            table='EventoParticipante',
        ),
        migrations.AlterModelTable(
            name='eventoperiodo',
            table='EventoPeriodo',
        ),
        migrations.AlterModelTable(
            name='eventotipo',
            table='EventoTitulo',
        ),
        migrations.AlterModelTable(
            name='eventovideo',
            table='EventoVideo',
        ),
    ]
