# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuariodetalhe'),
        ('evento', '0003_auto_20160821_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoConvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
                ('usuario_convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.UsuarioDetalhe')),
            ],
        ),
    ]
