# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_auto_20160612_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoparticipante',
            name='confirmado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
