# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_auto_20160612_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem_divulgacao',
            field=models.ImageField(default='palestra.jpg', upload_to='', verbose_name='Imagem de divulgação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoanexo',
            name='titulo_anexo',
            field=models.CharField(default='teste anexo', max_length=50, verbose_name='Título do anexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventovideo',
            name='titulo_video',
            field=models.CharField(default='teste video', max_length=50, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventoavaliacao',
            name='nota',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nota'),
        ),
    ]
