# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_auto_20160712_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='pais',
        ),
        migrations.AlterModelTable(
            name='eventotipo',
            table='EventoTipo',
        ),
    ]
