# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_auto_20160712_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoparticipante',
            name='presente',
            field=models.BooleanField(default=False, verbose_name='presença'),
        ),
        migrations.AlterField(
            model_name='eventoparticipante',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
